name: Deploy
on:
  push:
    branches:
      - main
env:
  IMAGE: ghcr.io/hasadna/open-bus-rides-history
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.IMAGE }}:buildcache-latest
          cache-to: type=registry,ref=${{ env.IMAGE }}:buildcache-latest,mode=max
      - uses: hasadna/hasadna-k8s/.github/actions/deploy@master
        with:
          app: openbus
          updates: ridesHistoryImage=${{ env.IMAGE }}:${{ github.sha }}
        env:
          HASADNA_K8S_DEPLOY_KEY: ${{ secrets.HASADNA_K8S_DEPLOY_KEY }}
