name: Deploy
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/hasadna/open-bus-rides-history:latest
            ghcr.io/hasadna/open-bus-rides-history:${{ github.sha }}
      - uses: hasadna/hasadna-k8s/.github/actions/deploy@master
        with:
          app: openbus
          updates: ridesHistoryImage=ghcr.io/hasadna/open-bus-rides-history:${{ github.sha }}
        env:
          HASADNA_K8S_DEPLOY_KEY: ${{ secrets.HASADNA_K8S_DEPLOY_KEY }}
